TOP=../..
include $(TOP)/configure/CONFIG

DIRS += undulator
DIRS += hxrss
DIRS += sxrss
DIRS += delta

include $(TOP)/configure/RULES_DIRS
#----------------------------------------
#  ADD RULES AFTER THIS LINE

